[package]
name = "raytracer"
version = "0.1.0"
authors = ["Ryan Moore <majoolwip@users.no.reply.github.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
crossbeam = "0.2.8"
fml = { path = "../../" }
